<?php

namespace EntityBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EntityBundle\Entity\Product;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * Class CommentRepository
 * @package EntityBundle\Repository
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param int $page
     * @param int $theNumberOnThePage
     * @return mixed
     */
    public function findByPage(int $page, int $theNumberOnThePage)
    {
        $lastResult  = $page * $theNumberOnThePage;
        $firstResult = $lastResult - $theNumberOnThePage;

        return $this
            ->createQueryBuilder('c')
            ->setFirstResult($firstResult)
            ->setMaxResults($theNumberOnThePage)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param Product $product
     * @param int     $page
     * @param int     $theNumberOnThePage
     * @return mixed
     */
    public function findByProduct(Product $product)
    {
        return $this->createQueryBuilder('c')
            ->where('c.product=:product')
            ->setParameter('product', $product)
            ->getQuery()
            ->getResult();
    }
}
